export const AREAS = [
    { value: "10", description: "الدسمـة" },
    { value: "11", description: "الدعيـــة" },
    { value: "12", description: "الدوحــة" },
    { value: "13", description: "الرابيــــة" },
    { value: "14", description: "الرحاب" },
    { value: "15", description: "الرقـــة" },
    { value: "16", description: "الرقعي" },
    { value: "17", description: "الرميثية" },
    { value: "18", description: "الروضة" },
    { value: "19", description: "الزهراء" },
    { value: "20", description: "السالمية" },
    { value: "21", description: "الســـرة" },
    { value: "22", description: "السلام" },
    { value: "23", description: "الشامية" },
    { value: "24", description: "الشرق" },
    { value: "25", description: "الشعـــب" },
    { value: "26", description: "الشويــخ" },
    { value: "27", description: "الصباحية" },
    { value: "28", description: "الصبية" },
    { value: "29", description: "الصليبخات" },
    { value: "3", description: "ابرق خيطان" },
    { value: "30", description: "الصوابر" },
    { value: "31", description: "الظهــر" },
    { value: "32", description: "العارضيـة" },
    { value: "33", description: "العدان" },
    { value: "34", description: "العديلية" },
    { value: "35", description: "العمريــة" },
    { value: "36", description: "الفحيحيل" },
    { value: "37", description: "الفردوس" },
    { value: "38", description: "الفروانية" },
    { value: "39", description: "الفنطاس" },
    { value: "4", description: "ابو حليفة" },
    { value: "40", description: "الفيحاء" },
    { value: "41", description: "القادسيــة" },
    { value: "42", description: "القريـــن" },
    { value: "43", description: "القصور" },
    { value: "44", description: "القلدسية" },
    { value: "45", description: "المنقـــف" },
    { value: "46", description: "المهبولة" },
    { value: "47", description: "النزهــة" },
    { value: "48", description: "الهيئة العامة لشئون القصر" },
    { value: "49", description: "اليرموك" },
    { value: "50", description: "بيـــان" },
    { value: "51", description: "جابر العلي" },
    { value: "52", description: "جليب الشيوخ" },
    { value: "53", description: "جنوب السرة" },
    { value: "54", description: "حطيـــن" },
    { value: "55", description: "حولي" },
    { value: "56", description: "خيطــان" },
    { value: "57", description: "خيطان الجنوبية" },
    { value: "58", description: "سلوى" },
    { value: "59", description: "صباح السالم" },
    { value: "6", description: "الاندلس" },
    { value: "60", description: "صباح الناصر" },
    { value: "61", description: "عبدالله السالم" },
    { value: "63", description: "غرناطة" },
    { value: "64", description: "قرطبة" },
    { value: "66", description: "كيفــان" },
    { value: "67", description: "مبارك الكبير" },
    { value: "68", description: "مشـــرف" },
    { value: "69", description: "هدية" },
    { value: "7", description: "الجابرية" },
    { value: "70", description: "القرين- منطقة1" },
    { value: "71", description: "المنصورية" },
    { value: "72", description: "كبفــان" },
    { value: "73", description: "ضاحية عبداله السالم" },
    { value: "74", description: "المرقاب" },
    { value: "75", description: "القصر" },
    { value: "76", description: "جنوب الرابية" },
    { value: "77", description: "العيون" },
    { value: "78", description: "القرين منقطقة 2" },
    { value: "79", description: "غرب الفنطاس" },
    { value: "8", description: "الجهـــراء" },
    { value: "80", description: "بنيد القار" },
    { value: "81", description: "مبارك عبدالله الجابر" },
    { value: "82", description: "القرين المنطقة 4" },
    { value: "83", description: "شمال الاحمدي" },
    { value: "84", description: "فهد الأحمد" },
    { value: "85", description: "جنوب الاحمدي" },
    { value: "86", description: "جنوب السرة - الزهراء" },
    { value: "87", description: "عبدالله مبارك الصباح" },
    { value: "88", description: "الشهداء" },
    { value: "89", description: "الشهداء" },
    { value: "9", description: "الخالدية" },
    { value: "90", description: "سعد العبدالله" },
    { value: "91", description: "جابر الاحمد" }
]